### ISSUE TITLE
Hi is there any way we can have a select all selection in the table?

### ISSUE THREAD

**Issue by harmeetsingh17** [muhimasri/angular-editable-table#8]
Firstly thank you for this project it really helps a lot just a minor enhancement if possible can we add a select all selection on the table?

**Comment by muhimasri** [comment]
You are very welcome! I can certainly add a select all option. I'll add it to the list of enhancements and work on it as soon as I can.

**Comment by muhimasri** [comment]
Hey there,

Here is an example from the Angular Material team with a select all option. They are using the same table component and can be applied to this example.

https://stackblitz.com/run?file=src%2Fapp%2Ftable-selection-example.ts

**Comment by mahindra-tashee** [comment]
Above url for stack blitz is not working ....can u reshare the url

**Comment by muhimasri** [comment]
Not sure why the link to stackblitz is not working, but here is a link to the table selection example from Angular Material site: https://material.angular.io/components/table/examples#table-selection

You should be able to see the code and open stackblitz from there

**Comment by mahindra-tashee** [comment]
hi muhimasri, thanks for reply can u please suggest any way to multi edit data in table.Below I have attached doc related to it just i want to change delete with edit.... which can edit multiple row so can please suggest any way to do so
![DeleteOutPut](https://user-images.githubusercontent.com/111742459/209076846-fffc08a4-670e-4796-b980-3c9473e41784.gif)

**Comment by muhimasri** [comment]
Hey there,

The code currently supports editing multiple rows, all you need to do is to get the selected rows (similar to what we do for delete) and then change all the "isEdit" prop to true when clicking edit. You can fork the example below on stackblitz and give it a try.

https://stackblitz.com/edit/angular-editable-table-part-4

**Comment by muhimasri** [comment]
Just pushed a new update to support "select all" for the table.
